apiVersion: v1
kind: PersistentVolume
metadata:
  name: waterlily-images-pv
  namespace: waterlily-filestore
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: waterlily-images
    fsType: ext4