apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waterlily-images-pvc
  namespace: waterlily-filestore
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: waterlily-images-pv